In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.preprocessing import StandardScaler

# 1 regressão linear

In [2]:
df_treino = pd.read_csv('https://raw.githubusercontent.com/Cayan-Portela/ceub/main/dados/insurance_treino.csv', sep = ';', decimal = ',')

In [3]:
df_treino.head(3)

age     sex    bmi  children smoker     region    charges
0   34  female  23.56         0     no  northeast  4992.3764
1   45  female  33.10         0     no  southwest  7345.0840
2   23    male  32.70         3     no  southwest  3591.4800

In [4]:
df_treino.drop(['region', 'bmi'], axis = 1, inplace = True)

In [5]:
df_treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1000 non-null   int64  
 1   sex       1000 non-null   object 
 2   children  1000 non-null   int64  
 3   smoker    1000 non-null   object 
 4   charges   1000 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 39.2+ KB


In [6]:
df_treino.loc[df_treino['smoker'] == 'no', 'smoker'] = 0
df_treino.loc[df_treino['smoker'] == 'yes', 'smoker'] = 1
df_treino.loc[df_treino['sex'] == 'male', 'sex'] = 0
df_treino.loc[df_treino['sex'] == 'female', 'sex'] = 1

In [7]:
df_treino['smoker'] = df_treino['smoker'].astype(int)
df_treino['sex'] = df_treino['sex'].astype(int)

## (a) Qual o objetivo em estimar o vetor de parâmetros $\^{\beta}$?

In [8]:
print('prever valores futuros')

prever valores futuros


## (b) Encontre o vetor de parâmetros $\^{\beta}$, utilizando as seguintes abordagens (indique os cálculos/pseudo-códigos utilizados partindo da equação 2):

### $i$. Solução analítica matricial.

In [9]:
def matriz_x(coluna, dados):
    
    n_ = dados.shape[0]
    col_1 = np.ones(n_)
    col_var = dados[coluna]
    X_mat = np.c_[col_1, np.array(col_var)]

    return X_mat

In [10]:
X_mat = matriz_x(coluna = ['age', 'sex', 'children', 'smoker'], dados = df_treino)
X_mat[:3]

array([[ 1., 34.,  1.,  0.,  0.],
       [ 1., 45.,  1.,  0.,  0.],
       [ 1., 23.,  0.,  3.,  0.]])

In [11]:
y = df_treino['charges']
y[:3]

0    4992.3764
1    7345.0840
2    3591.4800
Name: charges, dtype: float64

In [12]:
Xlx = X_mat.T @ X_mat
Xlx

array([[1.000000e+03, 3.920900e+04, 4.820000e+02, 1.096000e+03,
        2.020000e+02],
       [3.920900e+04, 1.735719e+06, 1.904800e+04, 4.364900e+04,
        7.721000e+03],
       [4.820000e+02, 1.904800e+04, 4.820000e+02, 5.250000e+02,
        8.200000e+01],
       [1.096000e+03, 4.364900e+04, 5.250000e+02, 2.622000e+03,
        2.280000e+02],
       [2.020000e+02, 7.721000e+03, 8.200000e+01, 2.280000e+02,
        2.020000e+02]])

In [13]:
inv_xlx = inv(Xlx)

In [14]:
betas = inv_xlx @ (X_mat.T) @ y
betas

array([-3075.26838274,   272.20653435,    57.34384981,   556.55795561,
       23799.89105225])

### $ii$. Decomposição QR.

In [15]:
# nao vai cair na prova

### $iii$. Gradiente descendente.

In [16]:
# eu nao sei pq essa nao funciona. boa sorte

In [17]:
X_mat = matriz_x(coluna=['age', 'sex', 'children', 'smoker'], dados=df_treino)
X_mat[:3]

array([[ 1., 34.,  1.,  0.,  0.],
       [ 1., 45.,  1.,  0.,  0.],
       [ 1., 23.,  0.,  3.,  0.]])

In [18]:
y = df_treino['charges']

y[:3]

0    4992.3764
1    7345.0840
2    3591.4800
Name: charges, dtype: float64

In [19]:
def grad_(X, B, Y):
    
    n_ = len(Y)
    grad = X.T @ (X @ B - Y) / n_

    return grad

In [20]:
betas = np.zeros(5)
betas

array([0., 0., 0., 0., 0.])

In [21]:
n_iter = 500
alpha = 0.01
betas_list = list()

for i in range(1, n_iter + 1):
    gradiente = grad_(X=X_mat, B=betas, Y=y)

    betas = betas - alpha * gradiente

    betas_list.append(betas)

C:\Users\xx\AppData\Local\Temp\ipykernel_9704\799805565.py:8: RuntimeWarning: invalid value encountered in subtract
  betas = betas - alpha * gradiente


In [22]:
betas

array([nan, nan, nan, nan, nan])

In [23]:
len(betas_list)

500

In [24]:
for i in range(0, len(betas_list)+1):
    if i % 50 == 0:
        print(betas_list[i-1])
print(betas_list[-1])

[nan nan nan nan nan]
[-3.78413571e+61 -1.67491793e+63 -1.83858790e+61 -4.21600095e+61
 -7.45265006e+60]
[-1.96317481e+122 -8.68932021e+123 -9.53842499e+121 -2.18722253e+122
 -3.86636633e+121]
[-1.01847704e+183 -4.50793943e+184 -4.94844718e+182 -1.13471094e+183
 -2.00583530e+182]
[-5.28376526e+243 -2.33867753e+245 -2.56720890e+243 -5.88677601e+243
 -1.04060891e+243]
[nan nan nan nan nan]
[nan nan nan nan nan]
[nan nan nan nan nan]
[nan nan nan nan nan]
[nan nan nan nan nan]
[nan nan nan nan nan]
[nan nan nan nan nan]


## (c) Calcule o Erro quadrático Médio na base de teste.

In [25]:
df_teste = pd.read_csv('https://raw.githubusercontent.com/Cayan-Portela/ceub/main/dados/insurance_teste.csv', sep = ';', decimal = ',')

In [26]:
df_teste.loc[df_teste['smoker'] == 'no', 'smoker'] = 0
df_teste.loc[df_teste['smoker'] == 'yes', 'smoker'] = 1
df_teste.loc[df_teste['sex'] == 'male', 'sex'] = 0
df_teste.loc[df_teste['sex'] == 'female', 'sex'] = 1

df_teste['smoker'] = df_teste['smoker'].astype(int)
df_teste['sex'] = df_teste['sex'].astype(int)

In [27]:
X_teste = matriz_x(coluna = ['age', 'sex', 'children', 'smoker'], dados = df_teste)

betas = [-3075.26838274, 272.20653435, 57.34384981, 556.55795561, 23799.89105225]

preditos = X_teste @ betas

erro = df_teste['charges'] - preditos

np.mean(erro ** 2)

48343255.08763409

# 2 regressão logística

In [28]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/Cayan-Portela/ceub/main/dados/bank_customer_treino.csv',
    usecols=['gender', 'age', 'credit_card', 'credit_score', 'churn']
    )

In [29]:
df.head(3)

credit_score  gender  age  credit_card  churn
0           564    Male   26            0      0
1           688    Male   45            0      0
2           784  Female   42            1      0

In [30]:
df.loc[df['gender'] == 'Male', 'gender'] = 0
df.loc[df['gender'] == 'Female', 'gender'] = 1

df['gender'] = df['gender'].astype(int)

## Newton-Raphson

In [31]:
def matriz_x(colunas, dados):
    
    n_ = dados.shape[0]
    col_1 = np.ones(n_)
    col_var = dados[colunas]

    X_mat = np.c_[col_1, np.array(col_var)]

    return X_mat

In [32]:
col_x = ['credit_score', 'gender', 'age', 'credit_card']

X_mat = matriz_x(col_x, df)
X_mat[:3]

array([[  1., 564.,   0.,  26.,   0.],
       [  1., 688.,   0.,  45.,   0.],
       [  1., 784.,   1.,  42.,   1.]])

In [33]:
y = df['churn']
y[:3]

0    0
1    0
2    0
Name: churn, dtype: int64

In [34]:
def beta_inicial(X):

    return np.zeros(X.shape[1])

In [35]:
def calcula_p(X, B):

    return np.exp(X @ B) / (1 + np.exp(X @ B))

In [36]:
def beta_update(X, W, y, p):

    return inv(X.T @ W @ X) @ X.T @ (y - p)

In [37]:
betas = beta_inicial(X_mat)
p = calcula_p(X_mat, betas)
W = np.diag(p)

for i in range(51):
    p = calcula_p(X_mat, betas)
    W = np.diag(p)
    beta_k1 = beta_update(X_mat, W, y, p)
    betas = betas + beta_k1

    if i % 5 == 0:
        print(f'Iteração {i}: {betas}')

Iteração 0: [-1.38614810e+00 -1.94814661e-04  1.47000394e-01  2.22232554e-02
 -1.21993081e-02]
Iteração 5: [-3.72955933e+00 -6.56375942e-04  4.87529214e-01  6.36438720e-02
 -4.92364054e-02]
Iteração 10: [-3.74527484e+00 -6.58073974e-04  4.89129824e-01  6.40429438e-02
 -4.90863632e-02]
Iteração 15: [-3.74574819e+00 -6.58123979e-04  4.89178253e-01  6.40560056e-02
 -4.90817729e-02]
Iteração 20: [-3.74576586e+00 -6.58125886e-04  4.89180083e-01  6.40564940e-02
 -4.90816108e-02]
Iteração 25: [-3.74576652e+00 -6.58125958e-04  4.89180152e-01  6.40565123e-02
 -4.90816047e-02]
Iteração 30: [-3.74576655e+00 -6.58125961e-04  4.89180154e-01  6.40565130e-02
 -4.90816045e-02]
Iteração 35: [-3.74576655e+00 -6.58125961e-04  4.89180154e-01  6.40565130e-02
 -4.90816045e-02]
Iteração 40: [-3.74576655e+00 -6.58125961e-04  4.89180154e-01  6.40565130e-02
 -4.90816045e-02]
Iteração 45: [-3.74576655e+00 -6.58125961e-04  4.89180154e-01  6.40565130e-02
 -4.90816045e-02]
Iteração 50: [-3.74576655e+00 -6.58125961e

## Gradiente descendente

In [38]:
scaler = StandardScaler()

In [39]:
credit_score = df['credit_score'].to_numpy()
age = df['age'].to_numpy()

credit_score = credit_score.reshape(-1, 1)
age = age.reshape(-1, 1)

age = scaler.fit_transform(age)
credit_score = scaler.fit_transform(credit_score)

In [40]:
df['age'] = age
df['credit_score'] = credit_score

In [41]:
df.head(3)

credit_score  gender       age  credit_card  churn
0     -0.884431       0 -1.231208            0      0
1      0.395807       0  0.555991            0      0
2      1.386959       1  0.273802            1      0

In [42]:
col_x = ['credit_score', 'gender', 'age', 'credit_card']

X_mat = matriz_x(col_x, df)
X_mat[:3]

array([[ 1.        , -0.88443118,  0.        , -1.23120783,  0.        ],
       [ 1.        ,  0.39580696,  0.        ,  0.55599141,  0.        ],
       [ 1.        ,  1.38695906,  1.        ,  0.27380206,  1.        ]])

In [43]:
y = df['churn']
y[:3]

0    0
1    0
2    0
Name: churn, dtype: int64

In [44]:
def beta_update(X, y, p):

    return -(1 / X.shape[0]) * (X.T) @ (y - p)

In [45]:
betas = beta_inicial(X_mat)
p = calcula_p(X_mat, betas)
alpha = .01

for i in range(50001):
    p = calcula_p(X_mat, betas)
    beta_k1 = beta_update(X_mat, y, p)
    betas = betas - alpha * beta_k1

    if i % 5000 == 0:
        print(f'Iteração {i}: {betas}')

Iteração 0: [-2.93000000e-03 -8.64136651e-05 -1.13583333e-03  1.18821393e-03
 -2.09833333e-03]
Iteração 5000: [-1.31846769 -0.06206294  0.25067299  0.66543523 -0.31585159]
Iteração 10000: [-1.52706723 -0.06320515  0.4090582   0.67410066 -0.16733653]
Iteração 15000: [-1.61043298 -0.06354396  0.45887172  0.67805773 -0.09990511]
Iteração 20000: [-1.64474054 -0.06366476  0.47701636  0.67975458 -0.07067197]
Iteração 25000: [-1.65904893 -0.06371158  0.48416337  0.6804721  -0.0582099 ]
Iteração 30000: [-1.66505115 -0.06373056  0.48708591  0.68077466 -0.05293323]
Iteração 35000: [-1.66757528 -0.06373842  0.48830132  0.68090217 -0.05070537]
Iteração 40000: [-1.66863787 -0.06374171  0.48881052  0.68095589 -0.04976589]
Iteração 45000: [-1.66908539 -0.06374309  0.48902454  0.68097852 -0.04936993]
Iteração 50000: [-1.66927391 -0.06374367  0.48911461  0.68098806 -0.04920308]


# 3 raízes

$x = \sqrt10 \\
x^2 = 10 \\
x^2-10=0 \\
f(x)=x^2-10 \\ 
f'(x)=2x$

$x_1=x_0-\frac{f(x_0)}{f'(x_0)} \\
x_1=x_0-\frac{x_0^2-10}{2x_0} \\
x_1=x_0-\frac{x_0^2}{2x_0}+\frac{10}{2x_0} \\
x_1=x_0-\frac{x_0}{2}+\frac{10}{2x_0} \\
x_1=\frac{x_0}{2}+\frac{10}{2x_0} \\
x_1=\frac{1}{2}(x_0+\frac{10}{x_0})$

In [46]:
def x_update(x):
    # return x - ((x**2-10) / (2*x))
    return (1/2) * (x + 10/x)

In [47]:
x_ = 1
for i in range(10):
    x_ = x_update(x_)

print(round(x_, 10))
print(round(x_, 10) == round(np.sqrt(10), 10))

3.1622776602
True


## 4

$f(x)=x^4-2x^3+2x-2 \\
f'(x)=4x^3-6x^2+2$

In [48]:
def x_update(x):
    return (x**4 - 2*x**3 + 2*x - 2) / (4*x**3 - 6*x**2 + 2)

In [49]:
x_ = 1000
count = 1

while x_ < 1 or x_ > 2:
    x_ -= x_update(x_)
    count += 1

print(round(x_, 8))
print(count)

1.83144651
25


## 5

$f(x)=3x^{1/3}=0 \\
f'(x)=x^{-2/3} \\
x_{n+1}=x_n-\frac{3x_n^{1/3}}{x_n^{-2/3}} \\
x_{n+1}=x_n-3x_n^{1/3+2/3} \\
x_{n+1}=x_n-3x_n \\
x_{n+1}=-2x_n$

In [50]:
def x_update(x):
    # return (3*x**(1/3)) / (x**(-2/3))
    return -2*x

In [51]:
x_ = .1

for i in range(10):
    x_ = x_update(x_)
    print(f'Passo {i+1}: {x_:.2f}')

Passo 1: -0.20
Passo 2: 0.40
Passo 3: -0.80
Passo 4: 1.60
Passo 5: -3.20
Passo 6: 6.40
Passo 7: -12.80
Passo 8: 25.60
Passo 9: -51.20
Passo 10: 102.40


## 6

$f(x)=x^4-5x^3+9x+3 \\
f'(x)=4x^3-15x^2+9=0$

In [52]:
def x_update(x):
    return (x**4 - 5*x**3 + 9*x + 3) / (4*x**3 - 15*x**2 + 9)

In [53]:
x_ = 150000
count = 1

while x_ <= 4 or x_ >= 6:
    x_ -= x_update(x_)
    count += 1

print(round(x_, 8))
print(count)

5.50101535
38


# Anotações extras

## Regressão linear

### Solução Analítica &rarr; $\beta = (X'X)^{-1} X'Y$
### Gradiente &rarr; $\beta = \beta - \alpha 2X'(X\beta-Y)$
### Newton-Raphson &rarr; $\beta = \beta - X'(X\beta-Y)(\beta'X')^{-1}$

## Regressão logística

### Solução Analítica &rarr; Não tem
### Gradiente &rarr; $\beta = \beta - \alpha [\frac{-1}{n} X'(y-p)]$
### Newton-Raphson &rarr; $\beta = \beta + (X'WX)^{-1} X'(y-p)$

## Raíz/Mínimo de Função

### Gradiente &rarr; $X = X - \alpha \cdot F(X) $
### Newton-Raphson &rarr; $X = X - \frac{F(X)}{F'(X)}$