1 - Crie um array Numpy 1D com 10 elementos e, em seguida, inverta a ordem dos elementos.

In [8]:
# resolva o Exercício aqui
import numpy as np
d1 = np.random.randint(1,101, size=10)
invert_d1 = d1[::-1]

In [9]:
d1

array([23, 58, 43, 86, 43, 70, 59,  7, 54, 80])

In [10]:
invert_d1

array([80, 54,  7, 59, 70, 43, 86, 43, 58, 23])

2 - Crie uma matriz 3x3 com números aleatórios entre 0 e 1.

In [4]:
# resolva o Exercício aqui
m3 = np.random.rand(3,3)

In [5]:
m3

array([[0.07336018, 0.5974477 , 0.11038828],
       [0.035208  , 0.75928261, 0.33701844],
       [0.43070029, 0.00846191, 0.84832823]])

3 - Dado um array 1D, encontre os índices dos elementos que são maiores que 5.

In [13]:
# resolva o Exercício aqui
ind = np.where(d1 > 5)

In [14]:
ind

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

4 - Dada uma matriz 4x4, calcule a soma dos elementos de cada coluna e cada linha.

In [22]:
#matriz 4x4 com valores aleatórios entre 1 e 10
m4 = np.random.randint(1, 11, size=(4, 4))
print("m4")
print(m4)

#soma dos elementos de cada linha (axis 1)
soma_linhas = np.sum(m4, axis=1)
print("Soma dos elementos de cada linha:")
print(soma_linhas)

#soma dos elementos de cada coluna (axis 0)
soma_colunas = np.sum(m4, axis=0)
print("Soma dos elementos de cada coluna:")
print(soma_colunas)


m4
[[4 8 4 3]
 [7 8 7 5]
 [4 4 6 4]
 [2 1 4 2]]
Soma dos elementos de cada linha:
[19 27 18  9]
Soma dos elementos de cada coluna:
[17 21 21 14]


5 - Crie uma matriz identidade 5x5 usando Numpy.

In [16]:
# resolva o Exercício aqui
mi = np.eye(5)

In [17]:
mi

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6 - Dado um array 1D, substitua todos os números pares por -1 sem alterar o array original.

In [18]:
# resolva o Exercício aqui
d1_copia = d1.copy()

In [19]:
d1_copia[d1_copia % 2 == 0] = -1

In [20]:
d1_copia

array([23, -1, 43, -1, 43, -1, 59,  7, -1, -1])

7 - Dadas duas matrizes, calcule a soma, a subtração, a multiplicação elemento a elemento e a multiplicação de matrizes.

In [24]:
# resolva o Exercício aqui
m1 = np.array([[11, 22], [33, 44]])
m2 = np.array([[55, 66], [77, 88]])

# Calcula a soma elemento a elemento
soma = m1 + m2

# Calcula a subtração elemento a elemento
subtracao = m1 - m2

# Calcula a multiplicação elemento a elemento
multiplicacao = m1 * m2

# Calcula a multiplicação das matrizes
multiplicacao_matrizes = m1.dot(m2)

# Exibe as matrizes e os resultados na tela
print("Soma elemento a elemento:")
print(soma)
print("Subtração elemento a elemento:")
print(subtracao)
print("Multiplicação elemento a elemento:")
print(multiplicacao)
print("Multiplicação das matrizes:")
print(multiplicacao_matrizes)


Soma elemento a elemento:
[[ 66  88]
 [110 132]]
Subtração elemento a elemento:
[[-44 -44]
 [-44 -44]]
Multiplicação elemento a elemento:
[[ 605 1452]
 [2541 3872]]
Multiplicação das matrizes:
[[2299 2662]
 [5203 6050]]


8 - Implemente uma função que calcula a distância euclidiana entre dois vetores usando Numpy.

In [ ]:
# resolva o Exercício aqui
# distancia euclidiana = d = sqrt((x2 - x1)^2 + (y2 - y1)^2)
def distancia_euclidiana(vetor1, vetor2):
    # usar os vetores como float evitaria erros na operação
    # Isso porque ele permite que sejam realizadas operações de ponto flutuante com precisão razoável, evitando problemas de arredondamento e truncamento
    vetor1 = vetor1.astype(float)
    vetor2 = vetor2.astype(float)
    
    # diferença entre os vetores
    diferenca = vetor1 - vetor2
    
    # quadrado da diferença
    quadrado_diferenca = diferenca ** 2
    
    # Soma os quadrados das diferenças
    soma_quadrados = np.sum(quadrado_diferenca)
    
    # Calcula a raiz quadrada da soma dos quadrados
    distancia = np.sqrt(soma_quadrados)
    
    return distancia


9 - Dado um array, encontre a média, a mediana e o desvio padrão dos elementos.

In [30]:
# primeiro modo
arr = np.random.rand(10)
import numpy as np

# média do array
media = np.mean(arr)

# mediana do array
mediana = np.median(arr)

# desvio padrão do array
desvio_padrao = np.std(arr)

print("Array: ", arr)
print("Média: ", media)
print("Mediana: ", mediana)
print("Desvio padrão: ", desvio_padrao)


Array:  [0.1028685  0.10230924 0.57905026 0.39785728 0.94621856 0.80192903
 0.57033284 0.83520754 0.89636467 0.7782466 ]
Média:  0.6010384535234474
Mediana:  0.6786484319323437
Desvio padrão:  0.29539377489884905


In [33]:
#segundo modo de fazer
import pandas as pd
novo = pd.DataFrame(arr)
novo.describe()

0
count  10.000000
mean    0.601038
std     0.311372
min     0.102309
25%     0.440976
50%     0.678648
75%     0.826888
max     0.946219

10 - Dada uma matriz, normalize-a de forma que seus elementos estejam no intervalo [0, 1].

In [35]:
# resolva o Exercício aqui
from sklearn.preprocessing import MinMaxScaler

# utilizando uma matriz do exercicio anterior
matriz = m2

# Criando o objeto MinMaxScaler
scaler = MinMaxScaler()

# Normalizando a matriz
matriz_normalizada = scaler.fit_transform(matriz)

print("Matriz: \n", matriz)
print("\nMatriz normalizada: \n", matriz_normalizada)


Matriz: 
 [[55 66]
 [77 88]]

Matriz normalizada: 
 [[0. 0.]
 [1. 1.]]


11 - Dado um conjunto de pontos, calcule a matriz de distâncias euclidianas entre todos os pares de pontos.

In [36]:
# resolva o Exercício aqui
from scipy.spatial.distance import pdist, squareform
# spatial.distance é usada para calcular distancia entre pontos
# pdist calcula a distancia entre todos os pares de pontos
# squareform tranforma um vetor de distancia em uma matriz contendo a distancia entre os pontos correspondentes
# Criando um conjunto de pontos com 5 pontos em 3 dimensões
pontos = np.random.rand(5, 3)

# Calculando a matriz (squareform) de distâncias(pdist) euclidianas (metric)
matriz_distancias = squareform(pdist(pontos, metric='euclidean'))

print("Conjunto de pontos:\n", pontos)
print("\nMatriz de distâncias euclidianas:\n", matriz_distancias)


Conjunto de pontos:
 [[0.16667177 0.32866423 0.59581209]
 [0.70924843 0.82020608 0.51600485]
 [0.1639932  0.24092856 0.16072369]
 [0.12091027 0.78408656 0.38689527]
 [0.92841528 0.14977738 0.34962749]]

Matriz de distâncias euclidianas:
 [[0.         0.73645911 0.4438543  0.50313999 0.82028077]
 [0.73645911 0.         0.87125795 0.60342001 0.72470006]
 [0.4438543  0.87125795 0.         0.58994096 0.79267541]
 [0.50313999 0.60342001 0.58994096 0.         1.02752195]
 [0.82028077 0.72470006 0.79267541 1.02752195 0.        ]]


12 - Implemente uma função que recebe um array e um valor e retorna o valor mais próximo do array.

In [37]:
# resolva o Exercício aqui
def valor_mais_proximo(array, valor):
    indice = np.abs(array - valor).argmin() 
    # np.abs calcula a diferença entre todos os elementos do array e o valor dado 
    # .argmin() retorna o índice do elemento do array com a menor diferença em relação ao valor dado como entrada
    return array[indice] #retorna o elemento com a menor diferença


In [44]:
array = np.random.rand(10)
valor_referencia = np.random.rand()
print(f'o array é: {array}')
print(f'o valor de referencia é: {valor_referencia}')
valor_proximo = valor_mais_proximo(array, valor_referencia)
print("Valor mais próximo:", valor_proximo)


o array é: [0.03860149 0.6864523  0.56950558 0.09260972 0.38272829 0.69690938
 0.05436691 0.04515611 0.35705899 0.64753347]
o valor de referencia é: 0.23650794726145785
Valor mais próximo: 0.3570589871638775


13 - Crie um array 2D 8x8 com um padrão de tabuleiro de xadrez usando 0s e 1s.

In [45]:
# Cria uma matriz 8x8 de zeros
tabuleiro = np.zeros((8, 8), dtype=int)
# Atribui valores 1 em uma "diagonal" de elementos alternados
tabuleiro[::2, 1::2] = 1 
''' são selecionadas as linhas ímpares (começando da segunda linha) e as colunas pares, 
e essas posições são preenchidas com o valor 1'''
tabuleiro[1::2, ::2] = 1
'''são selecionadas as linhas pares e as colunas ímpares, 
e essas posições são preenchidas com o valor 1'''
print(tabuleiro)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#segunda forma
# Cria um array 4x4 com o padrão 0-1
padrao = np.array([[0, 1], [1, 0]])
# Repete o padrão nos dois eixos para criar um array 8x8
tabuleiro = np.tile(padrao, (4, 4))
# Imprime o tabuleiro
print(tabuleiro)


14 - Implemente uma função que recebe um array e um valor e retorna o índice do elemento mais próximo do valor no array.

In [ ]:
# resolva o Exercício aqui


15 - Dado um array 1D, calcule a autocorrelação do array.

In [46]:
# resolva o Exercício aqui
auto_c = np.correlate(d1, d1, mode='full')
#np.correlate('array de entrada', 'array para correlacao', modo de calculo - full é padrão)

In [47]:
auto_c

array([ 1840,  5882,  6733, 10965, 13417, 16110, 21357, 20619, 23475,
       32733, 23475, 20619, 21357, 16110, 13417, 10965,  6733,  5882,
        1840])

16 - Implemente uma função que retorna a matriz de covariância entre duas variáveis de entrada usando Numpy.

In [49]:
# resolva o Exercício aqui
# array com as observações das variáveis x e y
X = np.array([[12, 23, 34], [45, 56, 67]])
# matriz de covariância entre x e y
cov = np.cov(X, rowvar=False)

print(cov)


[[544.5 544.5 544.5]
 [544.5 544.5 544.5]
 [544.5 544.5 544.5]]


17 - Implemente uma função que calcula o produto interno entre dois vetores usando Numpy.

In [50]:
# resolva o Exercício aqui
def produto_interno(v1, v2):
    return np.dot(v1, v2)

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(produto_interno(v1, v2))

32


18 - Dado um array 1D, calcule a diferença entre os elementos consecutivos.

In [52]:
# resolva o Exercício aqui
diff = np.diff(d1)
print(diff)

[ 35 -15  43 -43  27 -11 -52  47  26]


19 - Dada uma matriz, calcule a transposta e a inversa da matriz usando Numpy.

In [55]:
# resolva o Exercício aqui
#matriz transposta
t_transposta = m1.transpose()

# Calculando a matriz inversa
t_inversa = np.linalg.inv(m1)

print("Matriz A:")
print(m1)
print("Matriz transposta de A:")
print(t_transposta)
print("Matriz inversa de A:")
print(t_inversa)


Matriz A:
[[11 22]
 [33 44]]
Matriz transposta de A:
[[11 33]
 [22 44]]
Matriz inversa de A:
[[-0.18181818  0.09090909]
 [ 0.13636364 -0.04545455]]


20 - Implemente uma função que recebe um array 1D e retorna um array com os elementos normalizados para que a soma dos elementos seja igual a 1 (distribuição de probabilidade).

In [ ]:
# resolva o Exercício aqui
def normalize_array(arr):
    arr_sum = np.sum(arr)
    normalized_arr = arr / arr_sum
    return normalized_arr
